### ISSUE TITLE
If statements/architecture detection

### ISSUE THREAD

**Issue by kirbyfan64** [palmer-dabbelt/pconfigure#2]
I've been toying with `pconfigure` lately and have come to a slight issue: is it possible to have anything like an if statement? For instance, would it be possible to add an extra source file or change a compiler option based on the current architecture?

Also, is it possible to save variables that aren't reserved? For instance, this:

```
x = 1
```

does not work.

**Comment by palmer-dabbelt** [comment]
If you want to do something complicated, you can always "CONFIG += myscript" -- if "Configfiles/myscript" is executable then pconfigure execute it and read stdout.  That's how I have to do a few things (work around some libraries that are different on OSX, for example).  It's a bit of a mess, but since cross compiling isn't properly supported I think it's OK for now -- I'm hoping to fix this sort of thing with the pconfigure++ rewrite, but it may be a way off depending on how busy I am with work stuff.

There's no way to set arbitrary variables.

**Comment by kirbyfan64** [comment]
Oh...that makes sense. Thanks!
